### ISSUE TITLE
mXparser v.4.0.0

### ISSUE THREAD

**Issue by mariuszgromada** [wingoku/Calculator#1]
Hi :-)

Thanks for using mXparser :-) I am happy to inform that i just released v.4.0.0 - this is much better lib than before.

https://github.com/mariuszgromada/MathParser.org-mXparser/releases/tag/v.4.0.0

Best regards

BTW: Please let me know your opinion on the lib :-)

**Comment by wingoku** [comment]
@mariuszgromada Thanks for letting me know. The library is good however I have a few suggestions that may improve the accessibility features of the lib.

Currently the parser can't figure out 3pi and throws Nan result. If the parser knows syntax for pi, e and other mathematical variables. it would be great.

**Comment by mariuszgromada** [comment]
Thanks! Constants are supported i.e. 3*pi

**Comment by wingoku** [comment]
I know. I meant if the expression is like 3pi, it won't be parsed by MXparser. However if there is a * in between the two syllables, it will get parsed & executed. Another thing is, x isn't recognized as multiply, one has to replace the x with *.
